---
url: "http://localhost:8000"
database:
#ou 127.0.0.1
  host: "pgadmin"
  dbname: "nflix"
  user: "postgres"
  password: "qaninja"
users:
  cat_manager:
    email: "tony@stark.com"
    pass: "pwd123"
  admin:
    email: "admin@nflix.com"
    pass: "123456"